### ISSUE TITLE
Configure NGINX reverse proxy

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Sprints#28]
Completion Criteria:
[x] Write configs for reverse proxy

**Comment by delianides** [comment]
Configs are written for reverse proxy. Other considerations are:

- [ ] SSL Termination
- [ ] Session Persistance

**Comment by delianides** [comment]
Nginx reverse proxy works. Configs are written based on the contents of etcd. Special attention will need to be made to ensure that the appropriate key is always valid (at least one entry). I would like to find a method to disable the specific site if the keys are empty. Otherwise the container will attempt to distribute traffic to containers that don't exist.

**Comment by dcs619** [comment]
Tested with multiple containers.  confd automatically rewrites when a container goes down and nginx balances traffic to the remaining containers.  Closing.
