### ISSUE TITLE
Research Meteor ETE testing

### ISSUE THREAD

**Issue by dcs619** [NewSpring/Sprints#44]
http://xolv.io/blog/2013/04/end-to-end-testing-for-web-apps-meteor

**Comment by dcs619** [comment]
Vision:
- Developers  automate the reliability of their software with the testing framework
- Developers never push broken code
- Admins prevent breaking code from going to production

**Comment by richarddubay** [comment]
For complete end-to-end testing, it looks like Casper and Nightwatch are the two best choices. 

Casper is a headless browser based testing framework using PhantomJS.

Nightwatch is a browser based testing framework using Selenium.

For our purposes, Casper will work best because it is headless (doesn't require a browser), we can set it up to run on save so that developers will always know if code they change breaks something, and it will integrate easily into the CI so that we can set up to run tests on deploy in the future.
